using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace Inmobiliaria
{
    public partial class VentaDepartamento : DevExpress.XtraEditors.XtraUserControl
    {
        private int id = 0;
        private static VentaDepartamento _instance;
        public static VentaDepartamento Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new VentaDepartamento();
                    return _instance;
         
            }
        }
        public VentaDepartamento()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            



        }




        private void BtnEditar_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {

            
            //DevExpress.XtraEditors.XtraUserControl nv = new NuevaVenta();
           
            
            //if (gridViewVentaDepartamento.SelectedRowsCount> 0)
            //{
            //    //id = gridViewVentaDepartamento.DataRowCount;
            //    //frm.lblId.Text = Convert.ToString(gridViewVentaDepartamento.GetFocusedRowCellValue("id_inmueble"));

            //}


            //if (!PnlContenedorPrincipalVentaDepartamento.Controls.Contains(VentaCasaDuplex.Instance))
            //{
            //    PnlContenedorPrincipalVentaDepartamento.Controls.Add(VentaCasaDuplex.Instance);
            //    VentaCasaDuplex.Instance.Dock = DockStyle.Fill;
            //    VentaCasaDuplex.Instance.BringToFront();
            //}
            //VentaCasaDuplex.Instance.BringToFront();

            //DialogResult rs = MessageBox.Show("Hola");
            //gridViewVentaDepartamento.GetFocusedRowCellValue
        }

        private void VentaDepartamento_Load(object sender, EventArgs e)
        {
           
        }

       
       

    }
}
